// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDataDir() {
  return window['go']['main']['App']['AppDataDir']();
}

export function CancelStream() {
  return window['go']['main']['App']['CancelStream']();
}

export function ClearMemory() {
  return window['go']['main']['App']['ClearMemory']();
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function GetAutoLearnEnabled() {
  return window['go']['main']['App']['GetAutoLearnEnabled']();
}

export function GetCompactionStatus() {
  return window['go']['main']['App']['GetCompactionStatus']();
}

export function GetMemories() {
  return window['go']['main']['App']['GetMemories']();
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetSkillContent(arg1) {
  return window['go']['main']['App']['GetSkillContent'](arg1);
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetToolList() {
  return window['go']['main']['App']['GetToolList']();
}

export function GetWorkingDir() {
  return window['go']['main']['App']['GetWorkingDir']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function LoadConversations() {
  return window['go']['main']['App']['LoadConversations']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function PickWorkingDir() {
  return window['go']['main']['App']['PickWorkingDir']();
}

export function ReloadSkills(arg1) {
  return window['go']['main']['App']['ReloadSkills'](arg1);
}

export function ResetAgent() {
  return window['go']['main']['App']['ResetAgent']();
}

export function SaveConversations(arg1) {
  return window['go']['main']['App']['SaveConversations'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetAutoLearnEnabled(arg1) {
  return window['go']['main']['App']['SetAutoLearnEnabled'](arg1);
}

export function SetMemory(arg1, arg2) {
  return window['go']['main']['App']['SetMemory'](arg1, arg2);
}

export function SetWorkingDir(arg1) {
  return window['go']['main']['App']['SetWorkingDir'](arg1);
}

export function StreamMessage(arg1) {
  return window['go']['main']['App']['StreamMessage'](arg1);
}
