// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppDataDir():Promise<string>;

export function CancelStream():Promise<void>;

export function ClearMemory():Promise<void>;

export function DeleteMemory(arg1:string):Promise<void>;

export function GetAutoLearnEnabled():Promise<boolean>;

export function GetCompactionStatus():Promise<string>;

export function GetMemories():Promise<Record<string, string>>;

export function GetModels(arg1:Record<string, any>):Promise<Array<main.ModelInfo>>;

export function GetSkillContent(arg1:string):Promise<string>;

export function GetSkills():Promise<Array<string>>;

export function GetToolList():Promise<Array<string>>;

export function GetWorkingDir():Promise<string>;

export function LoadConversations():Promise<Array<main.PersistedConversation>>;

export function LoadSettings():Promise<main.PersistedSettings>;

export function PickWorkingDir():Promise<string>;

export function ReloadSkills(arg1:string):Promise<void>;

export function ResetAgent():Promise<void>;

export function SaveConversations(arg1:Array<main.PersistedConversation>):Promise<void>;

export function SaveSettings(arg1:main.PersistedSettings):Promise<void>;

export function SetAutoLearnEnabled(arg1:boolean):Promise<void>;

export function SetMemory(arg1:string,arg2:string):Promise<void>;

export function SetWorkingDir(arg1:string):Promise<void>;

export function StreamMessage(arg1:Record<string, any>):Promise<void>;
