package autolearn

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSanitizeName(t *testing.T) {
	tests := []struct {
		in, want string
	}{
		{"Test Driven Go", "test-driven-go"},
		{"my_skill!", "my_skill"},
		{"hello world---foo", "hello-world-foo"},
		{"---leading-and-trailing---", "leading-and-trailing"},
		{"中文 skill", "skill"},
		{"ABC", "abc"},
		// Length cap
		{"this-is-a-very-very-long-skill-name-that-exceeds-sixty-characters-limit", ""},
	}
	for _, tt := range tests {
		got := sanitizeName(tt.in)
		// For length-cap case we expect either empty or shortened.
		if tt.want != "" && got != tt.want {
			t.Errorf("sanitizeName(%q) = %q, want %q", tt.in, got, tt.want)
		}
		if strings.ContainsAny(got, " \t\n!@#$%^&*()") {
			t.Errorf("sanitizeName(%q) = %q contains illegal chars", tt.in, got)
		}
	}
}

func TestParseWorkflowBlocks_SingleBlock(t *testing.T) {
	resp := `WORKFLOW_START
NAME: test-driven-go
TRIGGER: 用户要求写 Go 函数时
DESCRIPTION: 强制 TDD 流程
STEP: 定义函数签名
STEP: 写失败测试
STEP: 实现函数直到测试通过
OUTPUT: 通过测试的 Go 代码
SOURCE: 用户在 3 次对话中都先写测试再实现
WORKFLOW_END`

	skills := parseWorkflowBlocks(resp)
	if len(skills) != 1 {
		t.Fatalf("expected 1 skill, got %d", len(skills))
	}
	s := skills[0]
	if s.Name != "test-driven-go" {
		t.Errorf("Name = %q", s.Name)
	}
	if s.Trigger != "用户要求写 Go 函数时" {
		t.Errorf("Trigger = %q", s.Trigger)
	}
	if s.Description != "强制 TDD 流程" {
		t.Errorf("Description = %q", s.Description)
	}
	if len(s.Steps) != 3 {
		t.Fatalf("Steps count = %d, want 3", len(s.Steps))
	}
	if s.Steps[0] != "定义函数签名" {
		t.Errorf("Steps[0] = %q", s.Steps[0])
	}
	if s.Output != "通过测试的 Go 代码" {
		t.Errorf("Output = %q", s.Output)
	}
	if s.Source != "用户在 3 次对话中都先写测试再实现" {
		t.Errorf("Source = %q", s.Source)
	}
}

func TestParseWorkflowBlocks_NoWorkflow(t *testing.T) {
	resp := "NOWORKFLOW"
	if skills := parseWorkflowBlocks(resp); len(skills) != 0 {
		t.Errorf("expected 0 skills for NOWORKFLOW, got %d", len(skills))
	}
}

func TestParseWorkflowBlocks_InvalidBlocks(t *testing.T) {
	// Missing NAME → invalid
	resp := `WORKFLOW_START
TRIGGER: 用户要求测试
STEP: 步骤 1
STEP: 步骤 2
STEP: 步骤 3
WORKFLOW_END`
	if skills := parseWorkflowBlocks(resp); len(skills) != 0 {
		t.Errorf("invalid block (no NAME) should be skipped, got %d", len(skills))
	}

	// No STEPs → invalid
	resp2 := `WORKFLOW_START
NAME: no-steps
TRIGGER: 用户要求
WORKFLOW_END`
	if skills := parseWorkflowBlocks(resp2); len(skills) != 0 {
		t.Errorf("invalid block (no STEPS) should be skipped, got %d", len(skills))
	}
}

func TestParseSkillMdBlocks(t *testing.T) {
	resp := `分析：这次对话体现了一个 TDD 工作流。

SKILL_START
---
name: test-driven-go
description: "强制 TDD 流程. Use when the user asks for Go functions."
---

# test-driven-go

> **Use when** the user asks for Go functions

## 步骤
1. 定义函数签名
2. 写失败测试
3. 实现函数

> Auto-generated by autolearn from conversation
SKILL_END

下一段说明...`

	blocks := parseSkillMdBlocks(resp)
	if len(blocks) != 1 {
		t.Fatalf("expected 1 block, got %d", len(blocks))
	}
	if !strings.Contains(blocks[0], "name: test-driven-go") {
		t.Errorf("block missing name frontmatter: %q", blocks[0])
	}
	if !strings.Contains(blocks[0], "Auto-generated by autolearn") {
		t.Errorf("block missing autogen footer: %q", blocks[0])
	}
}

func TestExtractSkillName(t *testing.T) {
	md := `---
name: test-driven-go
description: "test"
---
# test-driven-go
`
	got := ExtractSkillName(md)
	if got != "test-driven-go" {
		t.Errorf("ExtractSkillName = %q, want test-driven-go", got)
	}

	// Missing name
	if got := ExtractSkillName("# no frontmatter"); got != "" {
		t.Errorf("expected empty for missing name, got %q", got)
	}
}

func TestSkillRenderSKILLMd(t *testing.T) {
	s := Skill{
		Name:        "test-driven-go",
		Trigger:     "asks for Go functions",
		Description: "强制 TDD 流程",
		Steps:       []string{"定义函数签名", "写失败测试", "实现函数"},
		Output:      "通过测试的 Go 代码",
		Source:      "用户在 3 次对话中重复此流程",
	}
	out := s.RenderSKILLMd()

	checks := []string{
		"name: test-driven-go",
		"description:",
		"Use when",
		"# test-driven-go",
		"## 概述",
		"强制 TDD 流程",
		"## 步骤",
		"1. 定义函数签名",
		"2. 写失败测试",
		"3. 实现函数",
		"## 输出",
		"通过测试的 Go 代码",
		"用户在 3 次对话中重复此流程",
	}
	for _, c := range checks {
		if !strings.Contains(out, c) {
			t.Errorf("RenderSKILLMd missing %q\n--- output ---\n%s", c, out)
		}
	}
}

func TestSkillWriteSKILLMd(t *testing.T) {
	tmp := t.TempDir()
	s := Skill{
		Name:        "test-driven-go",
		Trigger:     "asks for Go functions",
		Description: "TDD 流程",
		Steps:       []string{"a", "b", "c"},
	}
	path, err := s.WriteSKILLMd(tmp)
	if err != nil {
		t.Fatalf("WriteSKILLMd failed: %v", err)
	}
	wantPath := filepath.Join(tmp, "test-driven-go", "SKILL.md")
	if path != wantPath {
		t.Errorf("path = %q, want %q", path, wantPath)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile failed: %v", err)
	}
	if !strings.Contains(string(data), "name: test-driven-go") {
		t.Errorf("written file missing frontmatter: %q", string(data))
	}
}

func TestSkillWriteSKILLMd_EmptyName(t *testing.T) {
	tmp := t.TempDir()
	s := Skill{Name: ""}
	if _, err := s.WriteSKILLMd(tmp); err == nil {
		t.Error("expected error for empty name")
	}
}

func TestWorkflowExtractor_Extract_NoWorkFlow(t *testing.T) {
	ext := &WorkflowExtractor{
		SummarizeFunc: func(ctx context.Context, prompt string) (string, error) {
			return "NOWORKFLOW", nil
		},
	}
	skills, err := ext.Extract(context.Background(), nil)
	if err != nil {
		t.Fatalf("Extract failed: %v", err)
	}
	if len(skills) != 0 {
		t.Errorf("expected 0 skills, got %d", len(skills))
	}
}

func TestWorkflowExtractor_ExtractSkillMd_NilDoc(t *testing.T) {
	ext := &WorkflowExtractor{
		SummarizeFunc: func(ctx context.Context, prompt string) (string, error) {
			return "", nil
		},
	}
	if _, err := ext.ExtractSkillMd(context.Background(), nil); err == nil {
		t.Error("expected error when SkillWriterDoc is empty")
	}
}

func TestWorkflowExtractor_ExtractSkillMd(t *testing.T) {
	ext := &WorkflowExtractor{
		SkillWriterDoc: "# skill-writer spec\n...",
		SummarizeFunc: func(ctx context.Context, prompt string) (string, error) {
			// Verify the prompt includes the spec.
			if !strings.Contains(prompt, "skill-writer spec") {
				t.Errorf("prompt missing spec reference")
			}
			return `SKILL_START
---
name: deploy-staging
description: "deploy to staging. Use when the user asks to deploy."
---
# deploy-staging

## 步骤
1. build
2. push
3. verify

> Auto-generated by autolearn from conversation
SKILL_END`, nil
		},
	}
	blocks, err := ext.ExtractSkillMd(context.Background(), nil)
	if err != nil {
		t.Fatalf("ExtractSkillMd failed: %v", err)
	}
	if len(blocks) != 1 {
		t.Fatalf("expected 1 block, got %d", len(blocks))
	}
	if !strings.Contains(blocks[0], "name: deploy-staging") {
		t.Errorf("block missing name: %q", blocks[0])
	}
}

func TestMaybeExtractWorkflow_Disabled(t *testing.T) {
	tmp := t.TempDir()
	dir := filepath.Join(tmp, "skills")
	al := New(nil, DefaultSettings()) // AutoLearn=false
	al.SetWorkflowDir(dir)

	ext := &WorkflowExtractor{
		SummarizeFunc: func(ctx context.Context, prompt string) (string, error) {
			t.Error("should not be called when AutoLearn=false")
			return "", nil
		},
	}
	if n := al.MaybeExtractWorkflow(context.Background(), nil, ext); n != 0 {
		t.Errorf("expected 0 when disabled, got %d", n)
	}
}

func TestMaybeExtractWorkflow_FallbackPath(t *testing.T) {
	tmp := t.TempDir()
	dir := filepath.Join(tmp, "skills")

	settings := DefaultSettings()
	settings.AutoLearn = true
	al := New(nil, settings)
	al.SetWorkflowDir(dir)

	// No SkillWriterDoc → fallback to Extract (structural).
	ext := &WorkflowExtractor{
		SummarizeFunc: func(ctx context.Context, prompt string) (string, error) {
			return `WORKFLOW_START
NAME: tdd-go
TRIGGER: user asks for Go functions
STEP: write test
STEP: run test
STEP: implement
OUTPUT: passing test
WORKFLOW_END`, nil
		},
	}

	n := al.MaybeExtractWorkflow(context.Background(), nil, ext)
	if n != 1 {
		t.Fatalf("expected 1 skill written, got %d", n)
	}
	path := filepath.Join(dir, "tdd-go", "SKILL.md")
	if _, err := os.Stat(path); err != nil {
		t.Errorf("expected SKILL.md at %s: %v", path, err)
	}
}

func TestMaybeExtractWorkflow_DirectPath(t *testing.T) {
	tmp := t.TempDir()
	dir := filepath.Join(tmp, "skills")

	settings := DefaultSettings()
	settings.AutoLearn = true
	al := New(nil, settings)
	al.SetWorkflowDir(dir)

	ext := &WorkflowExtractor{
		SkillWriterDoc: "# skill-writer spec",
		SummarizeFunc: func(ctx context.Context, prompt string) (string, error) {
			return `SKILL_START
---
name: deploy-staging
description: "deploy. Use when the user asks to deploy."
---

# deploy-staging
SKILL_END`, nil
		},
	}

	n := al.MaybeExtractWorkflow(context.Background(), nil, ext)
	if n != 1 {
		t.Fatalf("expected 1 skill, got %d", n)
	}
	path := filepath.Join(dir, "deploy-staging", "SKILL.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("expected SKILL.md: %v", err)
	}
	if !strings.Contains(string(data), "name: deploy-staging") {
		t.Errorf("written SKILL.md missing name: %q", string(data))
	}
}

func TestMaybeExtractWorkflow_NoDir(t *testing.T) {
	settings := DefaultSettings()
	settings.AutoLearn = true
	al := New(nil, settings)
	// No workflow dir set.

	ext := &WorkflowExtractor{
		SummarizeFunc: func(ctx context.Context, prompt string) (string, error) {
			t.Error("should not be called when dir is empty")
			return "", nil
		},
	}
	if n := al.MaybeExtractWorkflow(context.Background(), nil, ext); n != 0 {
		t.Errorf("expected 0 when no dir set, got %d", n)
	}
}
